### ISSUE TITLE
Nicknames in Servers

### ISSUE THREAD

**Issue by Randall-Scharpf** [Wendelstein7/DiscordUnitCorrector#24]
## Description ##

When the bot corrects a user in a server, the user is referred to by their user tag, not by their nickname. Given that it is more likely that a user is called by their nickname than their real name, the bot should also call users by that name.

## Example failure case ##
![image](https://user-images.githubusercontent.com/43557842/123900090-05905480-d92e-11eb-8f51-362222d56286.png)

## Proposed Fixes ##
 * Change `message.author.name` to `message.author.display_name` in https://github.com/Wendelstein7/DiscordUnitCorrector/blob/8d5743359b9c7c4485de9101a4ebf2e25fb5b065/unitbot.py#L43

**Comment by Randall-Scharpf** [comment]
I'm planning to give a shot to fixing this bug some time in the next few days. If you have any other ideas for fixes to propose, or if you see any issues with the fix I proposed, I'm all ears. If you're interested in fixing the bug yourself, go ahead and assign yourself to it, and I'll just leave you to fixing it.
Also, I'd like confirmation that this is in fact a bug and not an intended design before I proceed in fixing it.

**Comment by Randall-Scharpf** [comment]
Can the labels `bug` and `good first issue` be added to this thread? Thanks

**Comment by ethanrusz** [comment]
I would be happy to take a shot at this one in a few days.

**Comment by ethanrusz** [comment]
I opened up #31 for this one.

**Comment by Shaquu** [comment]
Thanks guys for resolving that. It landed on beta branch.

**Comment by Randall-Scharpf** [comment]
merged into beta
